### ISSUE TITLE
Check compatibility with phantomjs 2.1.1

### ISSUE THREAD

**Issue by jpnelson** [skatejs/web-components#11] opened 2016-09-08 23:43 UTC
This happens in unit tests: 

```
    ERROR: 'TypeError: Attempting to configurable attribute of unconfigurable property.'
```

**Comment by mitermayer** [comment] 2016-09-19 02:53
Whats the current state of this issue ?

**Comment by jpnelson** [comment] 2016-09-20 00:44
@mitermayer I haven't had a look at this yet, I think a good first step would be to try to run the named slots test suite with phantomjs 2.1.1

**Comment by treshugart** [comment] 2016-09-20 01:03
This is the problem: https://github.com/ariya/phantomjs/issues/13895. The issue is in named slots when trying to override anything on a DOM node.

**Comment by treshugart** [comment] 2016-09-20 01:14
Closing this as I've opened a bug in named-slots to address it there.

**Closed as completed by treshugart** 2016-09-20 01:14 UTC
